name: Build Signed Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Extract ZIP
        run: |
          unzip -o socialscienceapp.zip
          shopt -s dotglob
          mv socialscienceapp-main/* .
          rm -rf socialscienceapp-main

      - name: Make Gradle executable
        run: chmod +x gradlew

